[package]
name = "play"
version = "0.1.0"
edition = "2018"

[features]
midi = ["rodio", "synthrs"]

[dependencies]
lazy_static = "1.4.0"
clap = "2.33.3"
tempfile = "3.2.0"
zstd = "0.9"
indicatif = "0.17.0-beta.1"
fast_image_resize = "0.4.0"
dialoguer = "0.9"
futures = "0.3"
bytes = "1.1.0"
rmp-serde = "0.15.5"
async-broadcast = "0.3.4"
simd-adler32 = "0.3.4"

[dependencies.synthrs]
git = "https://github.com/gyng/synthrs"
optional = true

[dependencies.rodio]
version = "0.14.0"
optional = true

[dependencies.image]
version = "0.23.14"
default-features = false

[dependencies.tokio]
version = "1.13"
features = ["io-std","net","time","macros","io-util","fs","rt-multi-thread"]

[dependencies.tokio-util]
version = "0.6.9"
features = ["codec"]

[dependencies.ansi_lib]
path = "../ansi_lib"

[dependencies.color_lib]
path = "../color_lib"

[dependencies.substation]
git = "https://github.com/alisww/substation.git"

[dependencies.subrip]
git = "https://github.com/alisww/substation.git"

[dependencies.serde]
version = "1"
features = ["derive"]

